---
# Ansible Galaxy requirements for DISA STIG compliance
# Note: The rhel9STIG role is included locally in the roles/ directory

collections:
  - name: ansible.posix
    version: ">=1.5.0,<1.6.0"
  - name: community.general
    version: ">=1.0.0,<2.0.0"

